services:
    poke_user.admin.account:
        class: Poke\UserBundle\Admin\AccountAdmin
        arguments: [~, Poke\UserBundle\Entity\Account, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "用户", label: "账号"}
