sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:


sonata_admin:
    title: PokeMonOnline
    title_logo: bundles/pokeuser/images/bikaqiu.jpg
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

    # templates:
    #     layout:  SonataAdminBundle::base.html.twig
    #     list_block: SonataAdminBundle:Block:wan_dashboard_welcome.html.twig

